dist: trusty
sudo: required

rvm:
  - 2.2.1

before_install:
  - sudo apt-get install -y --force-yes build-essential ca-certificates git curl
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update
  - sudo apt-get install -y --force-yes gradle

install:
  - gem install json colorize nokogiri rubocop
  - git clone https://github.com/TwilioDevEd/twilio-api-faker.git
  - sudo cp twilio-api-faker/keystore/twilio_fake.pem /usr/local/share/ca-certificates/twilio_fake.crt
  - sudo update-ca-certificates

script:
  - ./run_twilio_api_faker.sh
  - ruby tools/snippet-testing/snippet_tester.rb -i

env:
  global:
    - NODE_PATH=/usr/local/lib/node_modules
    - NODE_TLS_REJECT_UNAUTHORIZED=0
    - FAKE_CERT_PATH=~/build/TwilioDevEd/api-snippets/twilio-api-faker/keystore/twilio_fake.pem
    - GRADLE_OPTS="-Dorg.gradle.daemon=true"
    - BASH=/bin/bash
    - BASH_SOURCE=/usr/local/bin/virtualenvwrapper.sh

matrix:
  include:
    - env: SNIPPET_LANGUAGE=python:curl
      language: python
      python: 2.7
      before_script:
        - sudo pip install -r requirements.txt
    - env: SNIPPET_LANGUAGE=node
      language: node
      node: latest
      before_script:
        - npm install
    - env: SNIPPET_LANGUAGE=ruby
      language: ruby
      before_script:
        - npm install
    - env: SNIPPET_LANGUAGE=php
      language: php
      php: 5.6
    - env: SNIPPET_LANGUAGE=java6
      language: java
      jdk: oraclejdk7
    - env: SNIPPET_LANGUAGE=java7
      language: java
      jdk: oraclejdk8
    - env: SNIPPET_LANGUAGE=csharp
      language: csharp
      mono: latest

addons:
  hosts:
    - api.twilio.com
    - chat.twilio.com
    - fax.twilio.com
    - ip-messaging.twilio.com
    - lookups.twilio.com
    - messaging.twilio.com
    - monitor.twilio.com
    - notifications.twilio.com
    - notify.twilio.com
    - preview.twilio.com
    - pricing.twilio.com
    - sync.twilio.com
    - taskrouter.twilio.com
    - video.twilio.com
    - wireless.twilio.com

notifications:
  slack:
    rooms:
      secure: Lbt/FIOBmBxqSH4aj4cctd+ygAWWN+IoEGRC1f7Wn1mgciSAWCGs6krUAqsxDCO+mU0bV0EdO2SNaB5vlmMCBA0tti6KYzR4M4OgkM/KwIUk1MBJcaD2gpMMbMK66xG74b5arPuO7GIWMjHgScKo04LGGeYOcw7RJZwB6CY+3eyFo4HLVkuWizNC2Qw2yq/2F///QywljWMbvJy1dUs0Ax3KG6NW8aRhj98TN/vnVAwC7BKCWYD0QQY+8qKf4Cbmt6W4riNufqm8ZQdLdgbRnLdKKxHUCEkARPzLvJhLrR4fB70hXI8iWcms0CcLPf2kjG8+iJso9MCai1SGdi4+duAoBUxHzCQTK2Q+8t7LKrfaOm9j0p46tk9VcI9GLUzVgE5XZpqssv+dqvf1tB/d+XTZu2M4I1fmZm0O7uo3XSWO25Vob6sqHKoRe1E0Ums4yCv5ZiMWuzvFan4CPIoC2Gxn1ZFWPU+//SDHolKIAG5j6bx9v+66UOv7EkBQVlW9CbZmK+12mRL0+gNxfWmFW23tgJhnuEYmJHqEGi3GWjzBY8YTQ5eiUJQXxV/NZknwAB4d/cHDEvbBlVrURqXG/E60ecKNw6QqTO8HMZXP8ROBPzKPSnwsY6TDPf1rrH3D9N4o9JyEhquuWG4NSovOcrzopgoNyfaEWbj0cLwxxs8=
    on_failure: always
    on_success: change

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
